### ISSUE TITLE
MetaStore – IndexOutOfBoundsException: No material found – Fallback?

### ISSUE THREAD

**Issue by joshmanderson** [aws/aws-dynamodb-encryption-java#221]
### Security issue notifications

If you discover a potential security issue in the Amazon DynamoDB Encryption Client we ask that you notify AWS Security via our [vulnerability reporting page](https://aws.amazon.com/security/vulnerability-reporting/). Please do **not** create a public GitHub issue.

### Problem:

When using `MostRecentProvider` and `MetaStore`, if an entry is removed from the backing DynamoDB table this results in the error `IndexOutOfBoundsException: No material found: materialName#0`, which is thrown from `MetaStore` [here](https://github.com/aws/aws-dynamodb-encryption-java/blob/master/sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/MetaStore.java#L242).

This seems brittle, and ideally if a record is removed from the backing table then a new one would be created in its place. That would be standard behavior for a cache. I attempted to do this myself by extending `MetaStore`, catching this error and calling `getOrCreate(materialName, version)`, which does create a new entry in the table but ultimately results in another error: `DynamoDBMappingException: Unable to decrypt envelope key`, which is thrown from `WrappedMaterialsProvider` [here](https://github.com/aws/aws-dynamodb-encryption-java/blob/master/sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/WrappedMaterialsProvider.java#L143).

Note that I also tried catching the error and returning the underlying `EncryptionMaterialsProvider` (`DirectKmsMaterialsProvider` in this case) instead of attempting to create a new record in the table, but that resulted in an `InvalidCipherTextException`.

### Solution:

It's not clear to me how this issue can be solved, as I don't have a good enough understanding of the way the `WrappedMaterialsProvider` works and why creating a new entry in the backing table results in the subsequent `DynamoDBMappingException: Unable to decrypt envelope key` error. I'm reaching out here to identify if there is a way to mitigate against the risk of entries being removed from the backing table. As it stands it seems that if this were to happen then the customer records we have encrypted in this fashion will become entirely inaccessible.

### Out of scope:

Is there anything the solution will intentionally NOT address?

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by joshmanderson** [comment]
I think it's worth asking this question as well, which may help me to understand why I'm running into some of these errors: How does `MostRecentProvider` and `MetaStore` actually work? How are customer records encrypted versus cached encryption materials/providers? This solution is incredibly obscure and complex, and the [documentation](https://docs.aws.amazon.com/dynamodb-encryption-client/latest/devguide/most-recent-provider.html) does not do a great job in explaining the behavior.

Namely: If I have a `MostRecentProvider` configured with a `MetaStore` which itself is configured with a `DirectKmsMaterialsProvider`, my assumption is that the actual customer records I'm encrypting by using that `MostRecentProvider` are ultimately encrypted using materials generated from the `DirectKmsMaterialsProvider`, but that those materials may or may not be present in either the `MostRecentProvider` in-memory LRU cache or the `MetaStore` DynamoDB table (i.e. the materials may be cached). Is my understanding correct? Further, how are the cache entries in the `MetaStore` DynamoDB table encrypted? Do they use the same `DirectKmsMaterialsProvider` that is fundamentally used to encrypt the actual customer records (based on my previous assumption) or some other mechanism?

**Comment by seebees** [comment]
@joshmanderson

To start, the error message is unfortunate.
It does not do a good job of describing the problem.
However, if there is a missing record in the `MetaStore`
then the `MetaStore` is *not* in a stable state.
The material stored in the `MetaStore` is not a cache.
It can not be recreated.

The material in the `MetaStore` is used to encrypt the items in the data table.
Let me take a concrete example to explain.
I'm going to simplify thing a little bit to hit the important point.
We can go into more detail if needed :)

Both the `MostRecentProvider` and the `CachingMostRecentProvider` are providing a key hierarchy.
In this example I assume that we are using the `DirectKmsMaterialProvider`
as the wrapped provider.

When the system goes to encrypt its first item, the `MetaStore` is empty.
So the wrapped `DirectKmsMaterialProvider` is called for material
and store this material in the `MetaStore`.
This same material is now used to encrypt the item.

On `decrypt` on a different host, the process is reversed.
When system wants to decrypt the item encrypted above
it will query the `MetaStore` for the appropriate version (v1 in this case).
Then the wrapped `DirectKmsMaterialProvider` is used to decrypt
this version and this material is used to decrypt the item.

But what about the "cache" you ask? :)
Well, the `CachingMostRecentProvider` does not hold onto this decrypted material indefinitely.
It is configured to poll the wrapped `DirectKmsMaterialProvider`
to make sure that it still has access to AWS KMS Key.

Also, if new versions are added to the `MetaStore` the `CachingMostRecentProvider`
will pick up these new version and will use only the lates version to encrypt.

I hope all of this explains why it is problematic if a version does not exist in the `MetaStore`.
This means that all items encrypted with this version can not be decrypted.

**Comment by joshmanderson** [comment]
I don't fully understand the concept of 'wrapped' material providers. To clarify my understanding, are you able to answer these explicit questions in a clearer way?
1. Given an underlying `DirectKmsMaterialProvider`, what encryption material is used to encrypt actual data? Is it the one produced by the `DirectKmsMaterialProvider` (i.e. is data encrypted in exactly the same way as if I weren't using `MetaStore` at all)? Or is it something else?
2. What encryption material is used to encrypt the encryption material from (1) above when it is persisted in the `MetaStore`?

A further question I have is: If I'm using `DirectKmsMaterialProvider`, what is the point of using `MetaStore` at all? It's clearly not used as a cache as you've stated (and as I've gleaned – accessing a record requires a call to KMS to decrypt the record anyway so no cache benefit occurs), so I'm unsure what benefit I would be getting from using it.

**Comment by lavaleri** [comment]
Hi @joshmanderson, I have attempted to answer your questions below. Please let me know if I can help clarify anything, or if you have any follow up questions! :)

(1)
If using the CachingMostRecentProvider with the MetaStore and DirectKmsMaterialProvider, then the first time you go to encrypt something, the MetaStore will generate the cryptographic materials ([it generates random bytes for encryption and auth keys](https://github.com/aws/aws-dynamodb-encryption-java/blob/master/sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/MetaStore.java#L338-L339)) that is ultimately used to encrypt your DDB items. That cryptographic material then gets stored in a separate DDB table, protected by the DirectKmsMaterialProvider.

(2)
The Cryptographic Materials Provider you configure with the MetaStore protects the materials persisted in the MetaStore’s DDB table. For example, if the MetaStore is configured with a DirectKmsMaterialProvider, then the configured KMS key is encrypting the material before the MetaStore stores it in the table, and decrypting it when the MetaStore retrieves those materials again.

(3)
The important thing here is that the MetaStore itself is not a cache, it just manages creation and storage of cryptographic materials. However the CachingMostRecentProvider *does* perform caching, allowing reuse of cryptographic materials. When used with the DirectKmsMaterialProvider it allows you to protect your DDB items with a KMS key, while minimizing the number of calls you need to make to KMS.

Let’s go back to our example using the CachingMostRecentProvider with the MetaStore and DirectKmsMaterialProvider. The first time you encrypt something with the CachingMostRecentProvider, a couple things happen. The MetaStore generates new encryption materials, and stores those materials, encrypted, in a DDB table. This requires a call to KMS to encrypt these materials before storing them in DDB. Next, the CachingMostRecentProvider caches this set of materials locally, and uses these materials to encrypt your DDB item. The second time you go to encrypt something, as long as these materials still exist in the cache, the CachingMostRecentProvider can use them immediately, requiring no call to KMS. From here, you should be able to see that you will only need to call KMS any time your set of cached materials expires (which you can set via TTL) or you rotate your materials (in Java this can be done by calling MetaStore’s [newProvider](https://github.com/aws/aws-dynamodb-encryption-java/blob/master/sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/ProviderStore.java#L53)).

The story is similar but slightly different on Decrypt. The CachingMostRecentProvider will see the DDB item you are trying to decrypt, and based on metadata attached to that record, will determine which set of materials in the MetaStore’s DDB it should try to use to decrypt the record (there will be multiple sets of encryption material in the Metastore’s DDB if you rotate your materials). The CachingMostRecentProvider will use its configured DirectKmsMaterialProvider to decrypt what’s in the Metastore’s DDB in order to get back the original set of encryption materials. This results in a Decrypt call to KMS. It then uses these materials to decrypt your DDB item, and caches those materials. The next time you need to decrypt an item that was encrypted using those same materials (assuming the TTL hasn’t expired yet), the CachingMostRecentProvider can use those materials immediately without requiring another KMS call.

**Comment by joshmanderson** [comment]
Thank you very much for the extended explanation! 😄 

I understand how this solution works now, and can confirm for myself that it is incompatible with my team's goals. We need our customer records to be encrypted using specific KMS keys, configured with a customized `DirectKmsMaterialProvider` – these records cannot be encrypted using the random materials produced by the `MetaStore`.

The original problem mentioned is no longer applicable to my use case, though it may still be worth considering any improvements you could make in this area for other teams (even just improving error messages or documentation perhaps).

Closing this issue.
