### ISSUE TITLE
More documentation or examples?

### ISSUE THREAD

**Issue by jhspaybar** [aws/aws-dynamodb-encryption-java#30]
I found the original blog post here https://aws.amazon.com/blogs/developer/client-side-encryption-for-amazon-dynamodb/ and have browsed through a bit of the code.  I was hoping there might be more documentation or examples, especially around rotation of keys.  It looks like it's possible to have multiple keys using the MostRecentProvider?

**Comment by mattsb42-aws** [comment]
`MostRecentProvider` can use a `MetaStore` with multiple keys, yes. On encrypt it looks for the most recent version (thus the name) of the material available in its `MetaStore`. It does not currently support automatic rotation of keys, but you can manually initiate this by calling `newProvider` on the `MetaStore`. This will create a new key with an incremented version, so the next time a `MostRecentProvider` uses that `MetaStore` table, the new key will be used.

Unfortunately, we don't have a lot in the way of example documentation at the moment. The original launch blog post[1] talks a bit about use, and this blog post[2] (unafilliated, but it's good content) talks about `MetaStore`, explaining how to use it. Another good resource is the AWS Forums[3], where we have helped others with their specific questions about using the client over time.

[1] https://aws.amazon.com/blogs/developer/client-side-encryption-for-amazon-dynamodb/
[2] https://javaknowledgestack.blogspot.com/2017/11/aws-kms-metastore-and.html
[3] https://forums.aws.amazon.com/forum.jspa?forumID=182&start=0

**Comment by ryanmunderwood** [comment]
Is there a way to have a nested object class inside a parent object class, and not encrypt the entire nested object, just some of it's properties?

**Comment by mattsb42-aws** [comment]
@ryanmunderwood Not with the current design of the DDB encryption client, no. That's one of the things on our list for future development in this space, but not something that we have a solid idea how to approach yet.

**Comment by ryanmunderwood** [comment]
@mattsb42-aws Thanks Matt. I know AWS just introduced encryption at rest for Dynamo back in FEB. I actually ended up creating a roll my own utility class for handling nested classes and their properties, but was just curious if this is something that was already supported under your project. Would be more than happy to share what I ended up doing (ended up borrowing your @DoNotEncrypt annotation within my utility class). Thanks!

**Comment by mattsb42-aws** [comment]
@ryanmunderwood  I think it would be good to have that conversation, yes. Until we have a better place to do it, just a new issue here would work. I know that we have considered partial attribute handling in the past and had rejected it to date due to concerns with data integrity handling.

@jhspaybar Last week we launched new documentation[1] about what the client is, how it works, and how to use it. Specific to your original question, this section[2] talks about the most recent provider. Does this new documentation cover your questions?

[1] https://docs.aws.amazon.com/dynamodb-encryption-client/latest/devguide/what-is-ddb-encrypt.html
[2] https://docs.aws.amazon.com/dynamodb-encryption-client/latest/devguide/most-recent-provider.html
