### ISSUE TITLE
Allow choice of algorithm rather than hard-coding CBC mode

### ISSUE THREAD

**Issue by jaxley** [aws/aws-dynamodb-encryption-java#52]
Was annoyed to find that CBC mode encryption is hard-coded in the code in the DynamoDBEncryptor class

`private static final String SYMMETRIC_ENCRYPTION_MODE = "/CBC/PKCS5Padding";`

This gets appended automatically to the algorithm set in the SecretKey object.

What would be nice is if you find that the algorithm `!"AES".equals(encryptionKey.getAlgorithm())`, then defer to whatever was set there, e.g. "AES/GCM/NoPadding"

Would then love to see GCM mode properly supported if that's detected.  

Or provide a way to override the relevant portions of the initialization to support additional cipher modes.

**Comment by SalusaSecondus** [comment]
Unfortunately, without larger data-format work (which we are planning to do), we are unlikely to support new block modes. Adding AES-CTR would be doable if there were sufficient call for it, but AES-GCM is far less likely as the format (as written) requires that the IV be equal to the block length. This is not correct for AES-GCM which should use a 96-bit nonce rather than a 128 bit nonce.

It is worth noting that AES-GCM offers no benefits over AES-CBC in the context of this library.
