### ISSUE TITLE
Automatically Ignore Global Table state fields [Feature Request]

### ISSUE THREAD

**Issue by pluttrell** [aws/aws-dynamodb-encryption-java#70]
If the Global Table feature is enabled, AWS automatically adds the following fields to each item: `aws:rep:updatetime`, `aws:rep:updateregion` and `aws:rep:deleting`. According to two AWS support techs we need to manually instruct this library to ignore these fields in the encryption and signing operations. 

For those using the AWS Java ObjectMapper, this means mapping these three fields in our entities. Since the replication code that AWS uses to implement the actual replication manages the state of these fields, I'm concerned that dangerous consequences could occur in situations like the following: Someone's application logic reads the entity - including the three fields, then writes the same values back 100ms later, but between these operations, the replication code updates the fields, so the net effect would be to revert the state that the replication code back to it's original state. Concurrent updates aren't limited to the replication code, but also concurrent application requests.

As such it seams only logical that no application code (or the ObjectMapper) should ever read or write any of these three fields, as such it seams that mapping these fields shouldn't be allowed. So if it's actually required by this library, I'd like to request a feature to automatically (or manually flip a flag) to ignore these three fields.

**Comment by johnwalker** [comment]
Thanks, this is definitely something we’re interested in supporting. Right now, there isn’t a good way to ignore just these three fields in the library, but there may be some workarounds we can try in the meantime. The mapper should work with these fields if @HandleUnknownAttributes is not present on the class. This will come with drawbacks if the model is ever changed, since signature validation will fail for old models that are reading data that was written with the new model.

**Comment by texastony** [comment]
Howdy @pluttrell ,

Following #68, in Pull Request #164, I tested the DynamoDB Encryption Client for Java with Global Tables. 
[Note that I specifically ignored the `aws:rep:*` fields when testing with Global Table Version 2017.11.29.](https://github.com/aws/aws-dynamodb-encryption-java/blob/636e07f65580f01782c3456fb8a2be88b8bc6b9b/examples/src/main/java/com/amazonaws/examples/AwsKmsEncryptedGlobal2017Object.java#L80-L107)

I also tested the migration path, from Global Table Version 2017.11.29 to Global Table Version 2019.11.21, [following the directions](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables_upgrade.html) provided by AWS DynamoDB. 

The same mapper configuration worked flawlessly. 

Since all future global tables will default to version 2019.11.21, which does not expose these special replication fields, we will not be implementing this feature. 
If you have any other questions please re-open this or open a new issue with us.

Much Obliged,
AWS Crypto Tools
